name: Manual workflow with parameters

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      compute_unit:
        description: 'Compute Unit to swap services staging vs. production'
        # Default value if no value is explicitly provided
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Validate compute_unit
      run: |
        if [[ -z "${{ inputs.compute_unit }}" ]]; then
          compute_unit="default compute unit!"
        elif [[ ${{ inputs.compute_unit }} =~ ^[0-9a-zA-Z\-_]+$ ]]; then
          compute_unit="${{ inputs.compute_unit }}"
        else
          echo "Invalid compute unit!" >&2
          exit 1
        fi
        echo "Hello $compute_unit"
